#ifndef LIB_DIALECT_CUTTINGBORED_CUTTINGBORED_TD_
#define LIB_DIALECT_CUTTINGBORED_CUTTINGBORED_TD_

include "CuttingBoredDialect.td"
include "CuttingBoredTypes.td"
include "CuttingBoredOps.td"
include "mlir/IR/BuiltinAttributes.td"
include "mlir/IR/OpBase.td"
include "mlir/Interfaces/InferTypeOpInterface.td"
include "mlir/Interfaces/SideEffectInterfaces.td"

#endif  // LIB_DIALECT_CUTTINGBORED_CUTTINGBORED_TD_
